services:
  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - '${PROJECT_ROOT_PATH}:/var/www/html'
    env_file:
      - '${PROJECT_ROOT_PATH}/.env'
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - "${PROJECT_ROOT_PATH}:/var/www/html"
    env_file:
      - '${PROJECT_ROOT_PATH}/.env'
    depends_on:
      - app

  db:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
    volumes:
      - '${DOCKER_DB_VOLUME_PATH}:/var/lib/mysql'

